/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uit.team;

import javax.swing.JFrame;

/**
 *
 * @author USER
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        setDefaultCloseOperation(HomeFrame.DISPOSE_ON_CLOSE) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sachTab = new javax.swing.JButton();
        phieuMuonTab1 = new javax.swing.JButton();
        hocVienTab2 = new javax.swing.JButton();
        dauSachTab2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sachTab.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        sachTab.setText("Quản lý sách");
        sachTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sachTabActionPerformed(evt);
            }
        });

        phieuMuonTab1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        phieuMuonTab1.setText("Quản lý Phiếu Mượn");
        phieuMuonTab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phieuMuonTab1ActionPerformed(evt);
            }
        });

        hocVienTab2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        hocVienTab2.setText("Quản lý học viên");
        hocVienTab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hocVienTab2ActionPerformed(evt);
            }
        });

        dauSachTab2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        dauSachTab2.setText("Quản lý Đầu sách");
        dauSachTab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dauSachTab2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hocVienTab2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(phieuMuonTab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sachTab, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(dauSachTab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sachTab, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hocVienTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phieuMuonTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dauSachTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sachTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sachTabActionPerformed
        // TODO add your handling code here:
        QLSachJFrame1 qlFrame = new QLSachJFrame1();
        qlFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sachTabActionPerformed

    private void phieuMuonTab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phieuMuonTab1ActionPerformed
        // TODO add your handling code here:
        QLPhieuMuonJFrame11 qlFrame = new QLPhieuMuonJFrame11();
        qlFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_phieuMuonTab1ActionPerformed

    private void hocVienTab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hocVienTab2ActionPerformed
        // TODO add your handling code here:
        QLHocVienJFrame qlFrame = new QLHocVienJFrame();
        qlFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hocVienTab2ActionPerformed

    private void dauSachTab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dauSachTab2ActionPerformed
        // TODO add your handling code here:
        QLDauSachJFrame1 qlFrame = new QLDauSachJFrame1();
        qlFrame.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_dauSachTab2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dauSachTab2;
    private javax.swing.JButton hocVienTab2;
    private javax.swing.JButton phieuMuonTab1;
    private javax.swing.JButton sachTab;
    // End of variables declaration//GEN-END:variables
}
